service: jobs-scraper
package:
  exclude:
    - node_modules/**
    - tst/**
    - analytics/**

provider:
  name: aws
  runtime: python3.6
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:DescribeTable
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
      # Restrict our IAM role permissions to
      # the specific table for the stage
      Resource:
        - "Fn::GetAtt": [ JobsTable, Arn ]
  
functions:
  scrape:
    handler: handler.scrape
    memory: 128
    timeout: 900
    events:
      - schedule:
          rate: rate(4 hours)
          enabled: false
          input:
            pages: 20
            ads_per_page: 50

resources:
  Resources:
    JobsTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: JobsTable
        AttributeDefinitions:
          -
            AttributeName: url
            AttributeType: S
        KeySchema:
          - 
            AttributeName: url
            KeyType: HASH
        BillingMode: PAY_PER_REQUEST
  
plugins:
  - serverless-python-requirements

custom:
  pythonRequirements:
    dockerizePip: true
